# Generated by Django 3.0.6 on 2020-05-17 07:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PY', 'Python'), ('DJ', 'Django'), ('RE', 'React'), ('JS', 'JavaScript'), ('ND', 'NODE'), ('MG', 'MongoDB'), ('MN', 'Mongoose'), ('NA', 'None')], default='NA', max_length=2), blank=True, size=None),
        ),
    ]
