# Generated by Django 3.0.6 on 2020-05-17 08:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200517_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='back_end_repo',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='front_end_repo',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='top_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PY', 'Python'), ('DJ', 'Django'), ('RH', 'React with hooks'), ('RC', 'React with classes'), ('RR', 'React Router'), ('JS', 'JavaScript'), ('NO', 'Node'), ('EX', 'Express'), ('MG', 'MongoDB'), ('MS', 'Mongoose'), ('AG', 'Angular'), ('PG', 'Postgres'), ('BS', 'Bootstrap'), ('HE', 'Heroku'), ('AW', 'Amazon Web Services'), ('DO', 'Digital Ocean'), ('JN', 'Jinja'), ('SC', 'Styled Components'), ('C3', 'CSS 3'), ('MU', 'Material UI'), ('MZ', 'Materialize'), ('SS', 'Sass'), ('LS', 'Less'), ('H5', 'HTML 5'), ('AX', 'Axios'), ('NA', 'None')], default='NA', max_length=2), blank=True, size=None),
        ),
    ]
