# Generated by Django 3.0.6 on 2020-05-17 18:56

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200517_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Course Project', 'Course Project'), ('Major Project', 'Major Project'), ('Week Project', 'Week Project'), ('Personal Day Project', 'Personal Day Project'), ('None', 'None')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Python', 'Python'), ('Django', 'Django'), ('React with hooks', 'React with hooks'), ('React with classes', 'React with classes'), ('React Router', 'React Router'), ('JavaScript', 'JavaScript'), ('Node', 'Node'), ('Express', 'Express'), ('MongoDB', 'MongoDB'), ('Mongoose', 'Mongoose'), ('Angular', 'Angular'), ('Postgres', 'Postgres'), ('Bootstrap', 'Bootstrap'), ('Heroku', 'Heroku'), ('Amazon Web Services', 'Amazon Web Services'), ('Digital Ocean', 'Digital Ocean'), ('Jinja', 'Jinja'), ('Styled Components', 'Styled Components'), ('CSS 3', 'CSS 3'), ('Material UI', 'Material UI'), ('Materialize', 'Materialize'), ('Sass', 'Sass'), ('Less', 'Less'), ('HTML 5', 'HTML 5'), ('Axios', 'Axios'), ('None', 'None')], max_length=253),
        ),
    ]
