# Generated by Django 3.0.6 on 2020-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200523_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='be_fa_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='fe_fa_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Course Project', 'Course Project'), ('Team Project', 'Team Project'), ('Major Project', 'Major Project'), ('Week Project', 'Week Project'), ('Personal Day Project', 'Personal Day Project'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
