# Generated by Django 3.0.6 on 2020-05-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200524_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='be_fa_icon',
        ),
        migrations.RemoveField(
            model_name='project',
            name='fe_fa_icon',
        ),
        migrations.AddField(
            model_name='project',
            name='web_icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
